name: 🚀 Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # or whatever your default branch is

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Grant precise permissions for Pages
    permissions:
      pages: write       # to publish
      contents: read     # to fetch your repo
      id-token: write    # for OIDC (required by new pages actions)

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Prepare Pages deployment
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 3) Upload everything in the repo as the Pages artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .           # adjust if your site is in a subfolder

      # 4) Publish to GitHub Pages
      - name: Deploy to Pages
        uses: actions/deploy-pages@v2
